modLoader="javafml"
license="Apache-2.0"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Trins-mods/Advanced-Solars-Classic-Edition/issues"

[[mods]]
modId="tamermod"
version="${version}"
displayName="Tamermod"
displayURL="https://github.com/Trins-mods/Advanced-Solars-Classic-Edition"
credits="xixixixixi"
authors="TamerixX"
description='''axxaxaxaxax'''
[[dependencies.advanced_solars]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.34,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.advanced_solars]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.advanced_solars]]
    modId="ic2"
    mandatory=true
    versionRange="[1.19.2-2.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.advanced_solars]]
    modId="ic2-classic-spmod"
    mandatory=false
    versionRange=""
    ordering="AFTER"
    side="BOTH"